window.CAYR_PRODUCTS = [
  {
    "id": 1,
    "category": "iPhone",
    "name": "iPhone 18 Pro Max",
    "brand": "Apple",
    "storage": "256GB",
    "price": 1299,
    "source": "https://www.apple.com/newsroom/2026/09/apple-debuts-iphone-18-pro-and-iphone-18-pro-max/",
    "image": "https://commons.wikimedia.org/wiki/Special:FilePath/IPhone_18_Pro_Max_(burgundy_model)_-_2.jpg?width=650",
    "tag": "NEW",
    "spec": "6.9” · A20 Pro",
    "blurb": "Premium display and pro camera system."
  },
  {
    "id": 2,
    "category": "iPhone",
    "name": "iPhone 18 Pro",
    "brand": "Apple",
    "storage": "256GB",
    "price": 1199,
    "source": "https://www.apple.com/newsroom/2026/09/apple-debuts-iphone-18-pro-and-iphone-18-pro-max/",
    "image": "",
    "tag": "NEW",
    "spec": "6.3” · A20 Pro",
    "blurb": "Powerful Pro performance in a compact size."
  },
  {
    "id": 3,
    "category": "iPhone",
    "name": "iPhone 17",
    "brand": "Apple",
    "storage": "256GB",
    "price": 929,
    "source": "https://www.apple.com/shop/buy-iphone/iphone-17",
    "image": "",
    "tag": "",
    "spec": "6.3” · A19",
    "blurb": "Unlocked connect-later reference price."
  },
  {
    "id": 4,
    "category": "iPhone",
    "name": "iPhone 17e",
    "brand": "Apple",
    "storage": "256GB",
    "price": 699,
    "source": "https://www.apple.com/shop/buy-iphone",
    "image": "",
    "tag": "",
    "spec": "6.1” · A19",
    "blurb": "A capable iPhone with everyday essentials."
  },
  {
    "id": 5,
    "category": "iPhone",
    "name": "iPhone Air",
    "brand": "Apple",
    "storage": "256GB",
    "price": 1099,
    "source": "https://www.apple.com/shop/buy-iphone",
    "image": "",
    "tag": "SLIM",
    "spec": "Thin profile",
    "blurb": "Lightweight iPhone in a sleek design."
  },
  {
    "id": 6,
    "category": "iPhone",
    "name": "iPhone 16",
    "brand": "Apple",
    "storage": "128GB",
    "price": 829,
    "source": "https://www.macrumors.com/2026/09/12/how-much-each-iphone-18-pro-model-costs/",
    "image": "",
    "tag": "",
    "spec": "6.1” · A18",
    "blurb": "Connect-later reference price."
  },
  {
    "id": 7,
    "category": "Samsung",
    "name": "Galaxy S26 Ultra",
    "brand": "Samsung",
    "storage": "256GB",
    "price": 1299.99,
    "source": "https://news.samsung.com/us/samsung-unveils-galaxy-s26-series-most-intuitive-galaxy-ai-phone-yet/",
    "image": "https://www.bigw.com.au/medias/sys_master/images/images/had/h06/140255117574174.jpg",
    "tag": "FLAGSHIP",
    "spec": "6.9” · S Pen",
    "blurb": "Galaxy flagship with versatile cameras."
  },
  {
    "id": 8,
    "category": "Samsung",
    "name": "Galaxy S26+",
    "brand": "Samsung",
    "storage": "256GB",
    "price": 1099.99,
    "source": "https://news.samsung.com/us/samsung-unveils-galaxy-s26-series-most-intuitive-galaxy-ai-phone-yet/",
    "image": "",
    "tag": "",
    "spec": "6.7” · 5G",
    "blurb": "A larger Galaxy S experience."
  },
  {
    "id": 9,
    "category": "Samsung",
    "name": "Galaxy S26",
    "brand": "Samsung",
    "storage": "256GB",
    "price": 899.99,
    "source": "https://news.samsung.com/us/samsung-unveils-galaxy-s26-series-most-intuitive-galaxy-ai-phone-yet/",
    "image": "",
    "tag": "",
    "spec": "6.3” · 5G",
    "blurb": "Powerful everyday Galaxy smartphone."
  },
  {
    "id": 10,
    "category": "Samsung",
    "name": "Galaxy A56 5G",
    "brand": "Samsung",
    "storage": "128GB",
    "price": 499.99,
    "source": "https://image-us.samsung.com/SamsungUS/business/solutions/industries/government/msrp-price-sheets/04072026/Samsung_HHP_MSRP_Price_File_%28March_2026%29.pdf",
    "image": "https://www.samsung-online.com.ua/uploads/shop/products/large/8f83d93860572ccfc20de6f81911de66.jpg",
    "tag": "VALUE",
    "spec": "6.7” · AMOLED",
    "blurb": "Mid-range Galaxy with a bright display."
  },
  {
    "id": 11,
    "category": "Samsung",
    "name": "Galaxy A36 5G",
    "brand": "Samsung",
    "storage": "128GB",
    "price": 399.99,
    "source": "https://image-us.samsung.com/SamsungUS/business/solutions/industries/government/msrp-price-sheets/04072026/Samsung_HHP_MSRP_Price_File_%28March_2026%29.pdf",
    "image": "",
    "tag": "",
    "spec": "6.7” · 5G",
    "blurb": "Accessible 5G connectivity."
  },
  {
    "id": 12,
    "category": "Samsung",
    "name": "Galaxy Z Fold7",
    "brand": "Samsung",
    "storage": "256GB",
    "price": 1999.99,
    "source": "https://www.samsung.com/us/smartphones/galaxy-z-fold7/buy/galaxy-z-fold7-256gb-unlocked-sku-sm-f966uzsaxaa/",
    "image": "",
    "tag": "FOLDABLE",
    "spec": "Foldable display",
    "blurb": "Tablet-like canvas in your pocket."
  },
  {
    "id": 13,
    "category": "Samsung",
    "name": "Galaxy Z Flip7",
    "brand": "Samsung",
    "storage": "256GB",
    "price": 1099.99,
    "source": "https://www.samsung.com/us/smartphones/galaxy-z-flip7/buy/",
    "image": "",
    "tag": "FOLDABLE",
    "spec": "Compact folding",
    "blurb": "Iconic flip design and cover screen."
  },
  {
    "id": 14,
    "category": "Google Pixel",
    "name": "Pixel 10 Pro XL",
    "brand": "Google",
    "storage": "128GB",
    "price": 1199,
    "source": "https://store.google.com/us/config/pixel_10_pro?hl=en-US&selections=eyJwcm9kdWN0RmFtaWx5IjoiY0dsNFpXeGZNVEJmY0hKdiJ9",
    "image": "",
    "tag": "PRO",
    "spec": "6.8” · Tensor G5",
    "blurb": "Pixel photo tools and large display."
  },
  {
    "id": 15,
    "category": "Google Pixel",
    "name": "Pixel 10 Pro",
    "brand": "Google",
    "storage": "128GB",
    "price": 999,
    "source": "https://store.google.com/us/config/pixel_10_pro?hl=en-US&selections=eyJwcm9kdWN0RmFtaWx5IjoiY0dsNFpXeGZNVEJmY0hKdiJ9",
    "image": "https://www.au.com/adobe/dynamicmedia/deliver/dm-aid--92d7fa66-8387-4e31-b7b4-0e006b020f58/pixel10p_moonstone_01_d92aceb2690e766f.jpg?preferwebp=true&quality=90",
    "tag": "",
    "spec": "6.3” · Tensor G5",
    "blurb": "Smartphone photography with Google AI."
  },
  {
    "id": 16,
    "category": "Google Pixel",
    "name": "Pixel 10",
    "brand": "Google",
    "storage": "128GB",
    "price": 799,
    "source": "https://blog.google/products-and-platforms/devices/pixel/google-pixel-10-pro-xl/",
    "image": "https://www.techspot.com/images/products/2025/smartphones/org/2025-08-27-product-7.jpg",
    "tag": "",
    "spec": "6.3” · Tensor G5",
    "blurb": "Camera and AI features at your fingertips."
  },
  {
    "id": 17,
    "category": "Google Pixel",
    "name": "Pixel 10a",
    "brand": "Google",
    "storage": "256GB",
    "price": 599,
    "source": "https://www.bestbuy.com/product/google-pixel-10a-256gb-unlocked-obsidian/J39TC8CZ7Y/sku/6668562",
    "image": "",
    "tag": "VALUE",
    "spec": "Pixel A-series",
    "blurb": "A practical way into the Pixel family."
  },
  {
    "id": 18,
    "category": "Other Android",
    "name": "OnePlus 15",
    "brand": "OnePlus",
    "storage": "256GB",
    "price": 899.99,
    "source": "https://www.oneplus.com/us/press/press-release/oneplus-launches-the-oneplus-15--the-ultimate-performance-flagship-smartphone-for-north-america",
    "image": "https://api.technopolis.bg/medias/Product-zoom-509337.jpg?context=bWFzdGVyfHJvb3R8MzA4NTQwfGltYWdlL2pwZWd8YURreUwyZzBZUzgxTURZNU5qWXlNVGMxTWpNMU1DOVFjbTlrZFdOMExYcHZiMjFmTlRBNU16TTNMbXB3Wnd8NTYxMjdlZDMzNDJmNzMyMWViN2ExMGU3OGNkZmY0MWI5MTk1MWQ4NGRjNGY4ZWM2ZjFiOTg4YjQ0ZGUzNWQ4MA",
    "tag": "PERFORMANCE",
    "spec": "165Hz · Snapdragon",
    "blurb": "Smooth performance and fast charging."
  },
  {
    "id": 19,
    "category": "Other Android",
    "name": "OnePlus 15",
    "brand": "OnePlus",
    "storage": "512GB",
    "price": 999.99,
    "source": "https://www.oneplus.com/us/press/press-release/oneplus-launches-the-oneplus-15--the-ultimate-performance-flagship-smartphone-for-north-america",
    "image": "https://api.technopolis.bg/medias/Product-zoom-509337.jpg?context=bWFzdGVyfHJvb3R8MzA4NTQwfGltYWdlL2pwZWd8YURreUwyZzBZUzgxTURZNU5qWXlNVGMxTWpNMU1DOVFjbTlrZFdOMExYcHZiMjFmTlRBNU16TTNMbXB3Wnd8NTYxMjdlZDMzNDJmNzMyMWViN2ExMGU3OGNkZmY0MWI5MTk1MWQ4NGRjNGY4ZWM2ZjFiOTg4YjQ0ZGUzNWQ4MA",
    "tag": "",
    "spec": "16GB RAM",
    "blurb": "More space for games and media."
  },
  {
    "id": 20,
    "category": "Other Android",
    "name": "Xiaomi 17",
    "brand": "Xiaomi",
    "storage": "256GB",
    "price": 828.99,
    "source": "https://miot-store.com/products/xiaomi-17-12gb-256gb-3d-ultrasonic-fingerprint-6-3-inch-xiaomi-hyperos-3-snapdragon-8-elite-gen-5-octa-core-nfc-network-5g-white",
    "image": "",
    "tag": "",
    "spec": "12GB RAM · 5G",
    "blurb": "Flagship-class compact Android phone."
  },
  {
    "id": 21,
    "category": "Other Android",
    "name": "Nothing Phone (3)",
    "brand": "Nothing",
    "storage": "256GB",
    "price": 799,
    "source": "https://us.nothing.tech/pages/pre-order-offer",
    "image": "https://lojae-s3-prd-files.radiopopular.pt/files/static/images/products/128563_0.jpg",
    "tag": "DESIGN",
    "spec": "12GB RAM",
    "blurb": "Distinctive minimalist design."
  },
  {
    "id": 22,
    "category": "Other Android",
    "name": "Nothing Phone (3)",
    "brand": "Nothing",
    "storage": "512GB",
    "price": 899,
    "source": "https://us.nothing.tech/pages/pre-order-offer",
    "image": "https://lojae-s3-prd-files.radiopopular.pt/files/static/images/products/128563_0.jpg",
    "tag": "",
    "spec": "16GB RAM",
    "blurb": "More storage for your everyday needs."
  }
];
